name: Build exe

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller
          # jeśli masz requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build exe
        run: pyinstaller --onefile transporty.py

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: transporty-exe
          path: dist/transporty.exe
